{
 "title": "Kafka Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Topics Partitions",
   "type": "graph",
   "description": "Kafka Topics Partitions",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_topic_partitions", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Kafka Topic Partition Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Topic Partition under replicated partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition",
     "legendFormat": "{{topic}} ({{partition}})"
    }
   ]
  },
  {
   "title": "Kafka Consumer Group Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag",
     "legendFormat": "Consumer: {{consumergroup}}  Topic: {{topic}} ({{partition}})"
    }
   ]
  },
  {
   "title": "Kafka Brokers",
   "type": "graph",
   "description": "Kafka Brokers Instances",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "instances" }
   ],
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Kafka Topic Partition  In Sync Replica",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_in_sync_replica",
     "legendFormat": "{{topic}} ({{patition}})"
    }
   ]
  }
 ]
}